### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by Answordy** [un-pogaz/Stonecutter-Damage#1]
Can you add a blacklist for mobs? Because stonecutter generates in villages and villagers kill themselves everytime with it.

**Comment by un-pogaz** [comment]
Hum, I hesitated betewen:

1. Create the tag as empty, that will be completed by additional datapack create by player, in according to its use
2. Create the tag with the `villager` entry arleady filled on it

The first was the most intended way of the datapack work, and so I would realy like to stay on this option as much as possible. But on view of IQ villagers, the second could will be nessecary.
What your opinion?

**Comment by Answordy** [comment]
Sorry for the late reply, I didnt see the notification about the comment and honestly I didnt even realize that it was a datapack up to this point what is a pleasant surprise since it provides easy configurability. Im personally fine with either, but the second option feels more friendly towards casual players who lack the knowledge of basic datapacks.
